<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>PrayerTimesManager</PackageId>
    <Version>1.0.3</Version>
    <Authors>Abdul Rahman</Authors>
    <Description>A .NET library for calculating Islamic prayer times (Fajr, Sunrise, Dhuhr, Asr, Sunset, Maghrib, Isha, Midnight) for any location and date, with support for multiple calculation methods, juristic schools, latitude adjustment methods, and time formats.</Description>
    <PackageTags>prayer-times;islam;islamic;salah;namaz;adhan;athan;fajr;dhuhr;asr;maghrib;isha</PackageTags>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/arahmancsd/PrayerTimesManager</PackageProjectUrl>
    <RepositoryUrl>https://github.com/arahmancsd/PrayerTimesManager</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
	<!-- <NoWarn>$(NoWarn);CS1591</NoWarn> -->
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
